### ISSUE TITLE
[SUGGESTION] Add subtypes of office software

### ISSUE THREAD

**Issue by Charlieseddon05** [OE-O/software-inc-plus#3]
**The Suggestion:**
<-- If you have kept the office software tab, I would like to suggest that you could make subtypes of office software like word, PowerPoint, Excel and other similar stuff. For the specs of the software, there would be different features like in word spell check, PowerPoint slide animations, you get the point. I think this is probably one of the less used softwares in the game and I think it would be more realistic to have these expanded features -->

**Additional Info** 

Base the features of the software off actual features of the software in real life

**Comment by cal3432** [comment]
This has already been implemented in another mod we've made:

OE-O | Office Software Overhaul

You can find it here:

https://steamcommunity.com/sharedfiles/filedetails/?id=2112429129
